# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

# 忽略警告⚠️
inhibit_all_warnings!
target 'LXDataSelectView' do
pod 'Masonry'

end
